[machine]
        cpus = 64
        cores_in_socket_order = false
        sockets = 2
        cores_per_socket = 16
        threads_per_core = 2
        numa_nodes = 2
        numa_node_ranges = [ 
                                [ 
                                    [0, 15], 
                                    [32, 47] 
                                ], 
                                [ 
                                    [16, 31],
                                    [48, 63]
                                ] 
                            ]

[graph]
        # color options: pid, command, parent
        color_by = "parent"

        interactive = true

        # webgl improves performance especially for large graphs, but may cause pixelation
        webgl = false

        gen_static = false
        static_res_width = 1920
        static_res_height = 1080

        launch_default_browser = true
        
        # non-empty path should end with '/'
        output_path = ""

        # static filetype options = png, jpeg, webp, svg, pdf, eps
        filetype = "png"
