[machine]
        cpus = 64
        sockets = 2
        cores_per_socket = 16
        threads_per_core = 2
        numa_nodes = 2

[graph]
        # color options: pid, command
        color_by = "pid"

        interactive = true
        gen_static = false
        static_res_width = 1920
        static_res_height = 1080
        launch_default_browser = true

        # static filetype options = png, jpeg, webp, svg, pdf, eps
        filetype = "png"
